In [16]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [17]:
#load the data
from google.colab import files
uploaded =files.upload()

Saving spamham.csv to spamham (1).csv


In [21]:
#read csv file
df = pd.read_csv('spamham (1).csv',encoding='latin-1')
#print the first row
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [22]:
#print the shape (get the number of rows and columns)
df.shape

(5728, 2)

In [23]:
# get the column names
df.columns

Index(['text', 'spam'], dtype='object')

In [24]:
#check for duplicate and remove
df.drop_duplicates(inplace=True)

In [25]:
#show if duplicate is there(number o rows and columns)
df.shape

(5695, 2)

In [26]:
#show the number of missing data(Nan,Nan) for each column
df.isnull().sum()

text    0
spam    0
dtype: int64

In [27]:
#download the stopword package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [29]:
#process text
def process_text(text):
  #1 remove punctuation
  #2 remove stopwords
  #3 return a list of clean textwords
  #1
  nopunch=[char for char in text if char not in string.punctuation]
  nopunch=''.join(nopunch)
  #2
  clean_words=[word for word in nopunch.split() if word.lower() not in stopwords.words('english')]
  #3
  return clean_words

In [30]:
#returning the words by comas as a list
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [31]:
#convert a collection of text to a matrix of token
from sklearn.feature_extraction.text import CountVectorizer
message_bow=CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [32]:
#split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(message_bow,df['spam'],test_size=0.20,random_state=0)

In [33]:
#get the shape of message_bow
message_bow.shape

(5695, 37229)

In [34]:
#create and train the naive bayes classifier and multinomial naive bayes
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB().fit(X_train,y_train)

In [35]:
#print prediction
print(classifier.predict(X_train))
#print the actual values
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [37]:
#evaluate the model (how good our model is)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=classifier.predict(X_train)
print( classification_report(y_train,pred))
print()
print('confusion Matrix:\n', confusion_matrix(y_train,pred))
print()
print('Accuracy  :',accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


confusion Matrix:
 [[3445   12]
 [   1 1098]]

Accuracy  : 0.9971466198419666


In [39]:
#print prediction
print(classifier.predict(X_test))
#print the actual values
print(y_test.values)
                      

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [40]:
#evaluate the model (how good our model is)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=classifier.predict(X_train)
print( classification_report(y_train,pred))
print()
print('confusion Matrix:\n', confusion_matrix(y_train,pred))
print()
print('Accuracy  :',accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


confusion Matrix:
 [[3445   12]
 [   1 1098]]

Accuracy  : 0.9971466198419666
